name: Django Buildpack

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: '${{ secrets.BASE_DIR }}'
      DISABLE_COLLECTSTATIC: '${{ secrets.DISABLE_COLLECTSTATIC }}'
      BUILDPACK_BUILDER: '${{ secrets.BUILDPACK_BUILDER }}'
      DOCKER_HUB_IMAGE_TAG: '${{ secrets.DOCKER_HUB_IMAGE_TAG || github.sha }}'
      DOCKER_HUB_REPO: '${{ secrets.DOCKER_HUB_REPO || github.repository }}'
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Pack CLI
      uses: buildpacks/github-actions/setup-pack@v5.0.0

    - name: Build app using Buildpacks
      run: |
        BASE_DIR="${{ env.BASE_DIR:-'src/' }}"
        DISABLE_COLLECTSTATIC="${{ env.DISABLE_COLLECTSTATIC:-1 }}"
        BUILDPACK_BUILDER="${{ env.BUILDPACK_BUILDER:-'gcr.io/buildpacks/builder' }}"
        DOCKER_HUB_REPO="${{ env.DOCKER_HUB_REPO:-github.repository }}"
        DOCKER_HUB_IMAGE_TAG="${{ env.DOCKER_HUB_IMAGE_TAG:-github.sha }}"

        pack build $DOCKER_HUB_REPO:$DOCKER_HUB_IMAGE_TAG \
          --path $BASE_DIR \
          --env "DISABLE_COLLECTSTATIC=$DISABLE_COLLECTSTATIC" \
          --builder $BUILDPACK_BUILDER

    - name: Login to Docker Hub
      id: docker_login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Check Docker Login
      if: steps.docker_login.outcome == 'failure'
      run: |
        echo "Failed to log in to Docker Hub. Please check your credentials."
        exit 1

    - name: Tag the container as latest as well as a specific version
      run: |
        docker tag $DOCKER_HUB_REPO:$DOCKER_HUB_IMAGE_TAG $DOCKER_HUB_REPO:latest

    - name: Push the specific version and latest tag to Docker Hub
      run: docker push $DOCKER_HUB_REPO --all-tags
